from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ==========================================================
# LOW-LEVEL BROWSER ACTION
# ==========================================================


class BrowserAction(BaseModel):
    """
    Represents one concrete browser operation.

    This is the low-level execution layer used by
    BrowserAgent / ActionExecutor.

    IMPORTANT:
        Credentials must never be placed directly into
        the LLM-generated BrowserAction.
    """

    action: Literal[
        "navigate",
        "click",
        "type",
        "scroll",
        "done",
    ]

    url: str | None = None
    selector: str | None = None
    text: str | None = None
    direction: Literal["up", "down"] | None = None

    reason: str


# ==========================================================
# SECURE LOGIN CREDENTIALS
# ==========================================================


class LoginCredentials(BaseModel):
    """
    Credentials required for an authenticated browser flow.

    Credentials are supplied by the application/runtime,
    not generated by the LLM.

    Security rules:

        - Never send this model to the LLM.
        - Never include password in browser observations.
        - Never print password in logs.
        - Never include password in exception messages.
    """

    username: str
    password: str

    @field_validator("username")
    @classmethod
    def validate_username(
        cls,
        value: str,
    ) -> str:

        value = value.strip()

        if not value:
            raise ValueError(
                "Login username cannot be empty."
            )

        return value

    @field_validator("password")
    @classmethod
    def validate_password(
        cls,
        value: str,
    ) -> str:

        if not value:
            raise ValueError(
                "Login password cannot be empty."
            )

        return value


# ==========================================================
# BROWSER OBSERVATION
# ==========================================================


class BrowserObservation(BaseModel):
    """
    Represents everything the agent observes after
    a browser action.

    The observation is fed back into the agent loop
    so the next action can be grounded in the current
    browser state.

    IMPORTANT:

        Observations must never contain raw credentials.
    """

    url: str
    title: str
    text: str
    screenshot_path: str


# ==========================================================
# VISUAL GROUNDING TARGET
# ==========================================================


class VisionTarget(BaseModel):
    """
    Represents a target located by the visual grounding
    system.

    Coordinates are optional because the target may not
    be found.
    """

    found: bool

    x: int | None = None
    y: int | None = None

    reason: str


# ==========================================================
# BROWSER AGENT STATE
# ==========================================================


class AgentState(BaseModel):
    """
    Runtime state of the low-level BrowserAgent loop.

    IMPORTANT:

        Do not store LoginCredentials here.

    Credentials should remain in the secure execution
    layer and should not become part of the agent's
    observable state.
    """

    task: str

    step: int = 0

    observation: BrowserObservation | None = None

    last_action: BrowserAction | None = None

    finished: bool = False

    error: str | None = None

    last_result: dict | None = None


# ==========================================================
# HIGH-LEVEL PLAN STEP
# ==========================================================


class PlanStep(BaseModel):
    """
    One high-level browser task.

    These actions describe WHAT should happen,
    not HOW the browser should perform it.

    Low-level browser operations such as click, type
    and scroll are handled later by BrowserAgent.

    Login is deliberately a high-level action.

    The login implementation will be responsible for
    obtaining credentials from the secure runtime rather
    than asking the LLM to generate them.
    """

    step_id: int

    action: Literal[
        "navigate",
        "search",
        "login",
        "extract",
    ]

    description: str

    target: str | None = None

    expected_result: str | None = None

    # ------------------------------------------------------
    # Description validation
    # ------------------------------------------------------

    @field_validator("description")
    @classmethod
    def validate_description(
        cls,
        value: str,
    ) -> str:

        value = value.strip()

        if not value:
            raise ValueError(
                "PlanStep description cannot be empty."
            )

        return value

    # ------------------------------------------------------
    # Target validation
    # ------------------------------------------------------

    @field_validator("target")
    @classmethod
    def validate_target(
        cls,
        value: str | None,
    ) -> str | None:

        if value is None:
            return None

        value = value.strip()

        if not value:
            raise ValueError(
                "PlanStep target cannot be empty."
            )

        return value

    # ------------------------------------------------------
    # Expected result validation
    # ------------------------------------------------------

    @field_validator("expected_result")
    @classmethod
    def validate_expected_result(
        cls,
        value: str | None,
    ) -> str | None:

        if value is None:
            return None

        value = value.strip()

        if not value:
            raise ValueError(
                "PlanStep expected_result cannot be empty."
            )

        return value


# ==========================================================
# HIGH-LEVEL BROWSER PLAN
# ==========================================================


class BrowserPlan(BaseModel):
    """
    Complete high-level execution plan generated by
    PerSitePlanner.

    The planner decides WHAT needs to happen.

    PlanRunner / BrowserAgent decide HOW it happens.
    """

    goal: str

    site: str

    steps: list[PlanStep] = Field(
        default_factory=list
    )

    # ------------------------------------------------------
    # Goal validation
    # ------------------------------------------------------

    @field_validator("goal")
    @classmethod
    def validate_goal(
        cls,
        value: str,
    ) -> str:

        value = value.strip()

        if not value:
            raise ValueError(
                "BrowserPlan goal cannot be empty."
            )

        return value

    # ------------------------------------------------------
    # Site validation
    # ------------------------------------------------------

    @field_validator("site")
    @classmethod
    def validate_site(
        cls,
        value: str,
    ) -> str:

        value = value.strip()

        if not value:
            raise ValueError(
                "BrowserPlan site cannot be empty."
            )

        return value

    # ------------------------------------------------------
    # Steps validation
    # ------------------------------------------------------

    @field_validator("steps")
    @classmethod
    def validate_steps(
        cls,
        steps: list[PlanStep],
    ) -> list[PlanStep]:

        if not steps:
            raise ValueError(
                "BrowserPlan must contain at least one step."
            )

        return steps


# ==========================================================
# PLAN STEP RESULT
# ==========================================================


class PlanStepResult(BaseModel):
    """
    Result produced after executing one PlanStep.
    """

    step_id: int

    action: Literal[
        "navigate",
        "search",
        "login",
        "extract",
    ]

    description: str

    finished: bool

    final_url: str | None = None

    final_title: str | None = None

    extracted_text: str | None = None

    error: str | None = None


# ==========================================================
# COMPLETE PLAN RESULT
# ==========================================================


class PlanRunResult(BaseModel):
    """
    Final result returned after PlanRunner executes
    a BrowserPlan.
    """

    goal: str

    site: str

    completed: bool

    steps: list[PlanStepResult] = Field(
        default_factory=list
    )

    final_result: str | None = None
