from dataclasses import dataclass


@dataclass(frozen=True)
class LoginConfig:
    """
    Trusted configuration for one authenticated site.

    This configuration is application-owned.

    It is never generated by the LLM.
    """

    login_url: str

    username_selector: str

    password_selector: str

    submit_selector: str

    username_env: str

    password_env: str

    success_url_contains: str | None = None


LOGIN_CONFIGS: dict[str, LoginConfig] = {
    "github.com": LoginConfig(
        login_url="https://github.com/login",
        username_selector="#login_field",
        password_selector="#password",
        submit_selector="input[type='submit']",
        username_env="GITHUB_USERNAME",
        password_env="GITHUB_PASSWORD",
    ),

    "saucedemo.com": LoginConfig(
        login_url="https://www.saucedemo.com/",
        username_selector="#user-name",
        password_selector="#password",
        submit_selector="#login-button",
        username_env="SAUCEDEMO_USERNAME",
        password_env="SAUCEDEMO_PASSWORD",
        success_url_contains="/inventory.html",
    ),
}